dist: bionic

addons:
  apt:
    packages:
    - lib32gcc1
    - libstdc++6
    - libstdc++6:i386
    - git

script:
  - bash ./steamcmd_help.sh

after_success:
  - .travis/push.sh

env:
  global:
  - secure: b/8xCJAGhU8YanVfhjBchNmj6pDO298I9+0U/xgbVUt/+XmcXf8WWjAoofOFPBXVwjpNz7EnV7jpI9C5ROPim1XTr94q3SJdQaE+7IqWcnz6P2Mh/iMh1G8Z6YCd0ch2kDc0Gg5KKc9GEje9VP08f8jOXhZqgQv3ajUhXfLVD7UFdBuqeGiaFdniKNWR0fcyG1vtDS7pLr0ZWFYcaWcsa2MzxozxgTks2yVZ4atBPyPppXIKLRJXz4RMpp+5PcekbJHsJj4BbPDlLyh+ajNyoOxbuVtGyKGYoed5H0GWs7rgFX0ve9TkHwWZ73ZYXvN5kQl5FaB+4QXCjbaimvmh6PlMXGPds7g/haR5BsTiZMJ1Lp+STYoCC+YLp5Nwr0T2+Zy574kUJjLt6p/tx8sksOU9148ZJc05o2KttN9PQFhi8sJPvz4/aPar3xCEHrCMzHWWyGkdgrhDAk1RZrWM0L5p/pvuy8bYEjbLb8y0BrFjE8t7u6FLVXOn6JTrve2EBTWPagQEgdzUiTNzlANq7c8jbMg6sh0JZ1uE0uU5zTFMsifoB0HCDxt3qGoNS9k1xwkH415X4OsedmSzkIHsTYOWofSb61iUu8nI5aT/yLWqLqwi9Gvvj96Zot9a2JT8GHbrw9Y0yZvahjJi4hn9c25fRTGQGnJT0HByq8a2Bks=
