language: bash
dist: xenial
sudo: required

addons:
  apt:
    packages:
    - lib32gcc1
    - libstdc++6
    - libstdc++6:i386
    - git

script:
  - bash ./steamcmd_help.sh

after_success:
  - .travis/push.sh
