---
# This workflow generates the output and pushes it to main branch

name: Generate Output

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Run steamcmd_help.sh
        run: ./steamcmd_help.sh

      - name: Push to main branch
        uses: Automattic/action-commit-to-branch@main
        with:
          branch: "main"
          commit_message: "GitHub Actions Build main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
