# This workflow generates the output and pushes it to master branch

name: Generate Output

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install steamcmd
      run: |
        sudo add-apt-repository universe
        sudo add-apt-repository multiverse
        sudo apt update
        sudo apt-get install steamcmd
      
    - name: Run steamcmd_help.sh
      run: ./steamcmd_help.sh

    - name: Push to built branch
      uses: Automattic/action-commit-to-branch@master
      with:
        branch: 'master'
        commit_message: 'GitHub Actions Build master'
      env:
        GITHUB_TOKEN: ${{ secrets.STEAMCMD_HELP_SECRET }} # Required
