---
# This workflow generates the output and pushes it to main branch

name: Generate Output

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1.1.4

      - name: Run steamcmd_help.sh
        run: ./steamcmd_help.sh

      - name: Push to ${{ github.ref }} branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: "${{ github.ref }}"
          commit_message: "GitHub Actions build: $(date --rfc-3339=date)"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
